name: "Dev-Build-Publish"

on:
  workflow_dispatch: {}

  push:
    branches:
      - "evmc_importer"

  pull_request:
    branches: [evmc_importer]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GC_BUCKET: "is-env-confg"
  VM_INSTANCE_NAME: "erigon-dev-explorer-1"
  VM_ZONE: "europe-west1-b"

jobs:
  publishing:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Login to GCP Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Checkout template repo
        uses: actions/checkout@v3

      - name: GCP auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_DFX_SERVER_JSON_KEY }}'

      - name: Updating scripts
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '.gcp'
          parent: false
          destination: ${{ env.GC_BUCKET }}/erigon

      - name: Building base Rust/DFX image
        uses: docker/build-push-action@v4
        with:
          # push-image: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/evmc_importer') ||  github.ref_type == 'tag' }}
          push: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/evmc_importer') }}
          context: .
          file: ./Dockerfile
          build-args: |
            UID=942
            GID=942
          tags: |
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/erigon:latest

